spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Dev: allow Flyway to create baseline
  flyway:
    baseline-on-migrate: true

logging:
  file:
    name: /tmp/keevo-dev.log
  level:
    root: DEBUG
    com.keevo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
