spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jpa:
    show-sql: false

  security:
    require-ssl: true

logging:
  level:
    root: WARN
    com.keevo: INFO

server:
  tomcat:
    max-threads: 200
    accept-count: 100
