package com.keevo.shared.infrastructure.persistence.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.Immutable;

import java.time.Instant;
import java.util.UUID;

/**
 * AuditLogJpaEntity — JPA mapping for the per-tenant {@code audit_log} table.
 *
 * <p>Story 1.8 — Immutable audit trail.
 *
 * <p><b>Immutability guarantees (double protection):</b>
 * <ol>
 *   <li>{@code @org.hibernate.annotations.Immutable} — Hibernate ignores any UPDATE flush
 *       for instances of this entity. Any accidental mutation is silently discarded.</li>
 *   <li>{@code @Column(updatable = false)} on {@code occurredAt} — redundant but explicit
 *       DDL constraint alignment.</li>
 * </ol>
 *
 * <p><b>No {@code tenantId} column</b> — isolation is provided by TenantContext +
 * {@code SchemaAwareMultiTenantConnectionProvider}, which routes all Hibernate sessions to
 * the correct {@code kv_xxxxxx} schema. The schema itself IS the tenant boundary.
 *
 * <p>Infrastructure layer only — never exposed to domain or application layers.
 */
@Entity
@Immutable
@Table(name = "audit_log")
public class AuditLogJpaEntity {

    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "user_id", updatable = false, nullable = false)
    private UUID userId;

    @Column(name = "entity_type", updatable = false, nullable = false, length = 50)
    private String entityType;

    @Column(name = "entity_id", updatable = false, nullable = false)
    private UUID entityId;

    @Column(name = "action", updatable = false, nullable = false, length = 80)
    private String action;

    @Column(name = "value_before", columnDefinition = "TEXT", updatable = false)
    private String valueBefore;

    @Column(name = "value_after", columnDefinition = "TEXT", updatable = false)
    private String valueAfter;

    /**
     * Set programmatically before save — {@code Instant.now()}.
     * NOT auto-generated by DB (we control the value for testability).
     */
    @Column(name = "occurred_at", nullable = false, insertable = true, updatable = false)
    private Instant occurredAt;

    /** Required no-arg constructor for Hibernate proxy. */
    protected AuditLogJpaEntity() {
    }

    public AuditLogJpaEntity(UUID id, UUID userId, String entityType, UUID entityId,
                              String action, String valueBefore, String valueAfter,
                              Instant occurredAt) {
        this.id          = id;
        this.userId      = userId;
        this.entityType  = entityType;
        this.entityId    = entityId;
        this.action      = action;
        this.valueBefore = valueBefore;
        this.valueAfter  = valueAfter;
        this.occurredAt  = occurredAt;
    }

    // ── Read-only accessors ───────────────────────────────────────────────────

    public UUID    getId()          { return id; }
    public UUID    getUserId()      { return userId; }
    public String  getEntityType()  { return entityType; }
    public UUID    getEntityId()    { return entityId; }
    public String  getAction()      { return action; }
    public String  getValueBefore() { return valueBefore; }
    public String  getValueAfter()  { return valueAfter; }
    public Instant getOccurredAt()  { return occurredAt; }
}
